spring:
  jwt:
    secret: 64461f01e1af406da538b9c48d801ce59142452199ff112fb5404c8e7e98e3ff
  # H2 Setting Info (H2 Console? ???? ?? ???? ??)
  h2:
    console:
      enabled: true  # H2 Console? ???? ?? (H2 Console? H2 Database? UI? ????? ??)
      path: /h2-console  # H2 Console? Path
  # Database Setting Info (Database? H2? ???? ?? H2?? ?? ??)
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root  # H2 ?? ? ??? username ?? (??? ??? ??)
    password: dltn5309 # H2 ?? ? ??? password ?? (??? ??? ??)
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create-drop     # DB ??? ?? (none, create, create-drop, update, validate)
    properties:
      hibernate:
        format_sql: true      # ?? ?? ?? (??)
        show_sql: true        # ?? ?? ??
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    s3:
      bucket: mentalhub1
    region:
      static: ap-northeast-2
    stack:
      auto: false
mail:
  address:
    admin: gustn5309@naver.com

    #sever:

  #servlet:
    #context-path: /api/v1




